### ISSUE TITLE
gex-tracker did not work as expected

### ISSUE THREAD

**Issue by MikeQin** [Matteo-Ferrara/gex-tracker#1]
Followed the README instructions, when run python main.py, I got the following errors:

C:\dev\GEX\gex-tracker\gex-tracker\main.py:11: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use("seaborn-dark")
Enter desired ticker:spx
Traceback (most recent call last):
  File "C:\Users\mikeq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 960, in json
    return complexjson.loads(self.content.decode(encoding), **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", 
line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", 
line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

  File "C:\dev\GEX\gex-tracker\gex-tracker\main.py", line 158, in <module>
    run(ticker)
  File "C:\dev\GEX\gex-tracker\gex-tracker\main.py", line 21, in run
    spot_price, option_data = scrape_data(ticker)
  File "C:\dev\GEX\gex-tracker\gex-tracker\main.py", line 41, in scrape_data
    json.dump(data.json(), f)
  File "C:\Users\mikeq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 968, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Matteo-Ferrara** [comment]
Try to enter the ticker in full capital letters, that is SPX instead of spx. Works for me
